/**
 * One-command local setup.
 *
 * Brings up the Supabase stack, applies migrations, seeds a fake season, and writes
 * apps/web/.env.local from the running stack's own keys.
 *
 * That last step is the reason this exists: the keys are printed by `supabase status` and
 * were previously copied by hand into a file nothing generates, which is the single thing
 * most likely to leave a new checkout showing an empty app with no obvious cause.
 *
 *   pnpm dev:setup
 */
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';

const step = (text: string) => console.log(`\n▸ ${text}`);
const ok = (text: string) => console.log(`  ✓ ${text}`);

function run(command: string, args: string[], opts: { quiet?: boolean } = {}): string {
  return execFileSync(command, args, {
    encoding: 'utf8',
    stdio: opts.quiet ? ['ignore', 'pipe', 'pipe'] : ['ignore', 'pipe', 'inherit'],
  });
}

function main() {
  // --- prerequisites ------------------------------------------------------
  step('Checking prerequisites');

  try {
    run('docker', ['info'], { quiet: true });
    ok('Docker is running');
  } catch {
    console.error(`
  ✗ Docker is not running.

    The Supabase stack (Postgres, Auth, PostgREST, Studio) runs in Docker. The
    Next.js app itself runs on Node directly — only the database side is containerised.

    Start Docker Desktop and run this again.
`);
    process.exit(1);
  }

  try {
    run('supabase', ['--version'], { quiet: true });
    ok('Supabase CLI is installed');
  } catch {
    console.error(`
  ✗ Supabase CLI not found.  brew install supabase/tap/supabase
`);
    process.exit(1);
  }

  // --- stack --------------------------------------------------------------
  step('Starting Supabase (first run pulls images, a few minutes)');
  try {
    run('supabase', ['start']);
  } catch {
    // Already running is not an error worth stopping for.
    ok('already running');
  }

  const status = JSON.parse(run('supabase', ['status', '-o', 'json'], { quiet: true })) as Record<
    string,
    string
  >;

  const apiUrl = status.API_URL ?? 'http://127.0.0.1:54321';
  const anonKey = status.ANON_KEY;
  const serviceKey = status.SERVICE_ROLE_KEY;

  if (!anonKey || !serviceKey) {
    console.error('  ✗ Could not read keys from `supabase status`.');
    process.exit(1);
  }
  ok(`API at ${apiUrl}`);

  // --- env ----------------------------------------------------------------
  step('Writing apps/web/.env.local');

  const env = [
    '# Generated by `pnpm dev:setup`. Local stack only — these keys are the well-known',
    '# Supabase development defaults and are safe in a repo checkout, but this file is',
    '# git-ignored regardless. Re-run dev:setup if you reset the stack.',
    `NEXT_PUBLIC_SUPABASE_URL=${apiUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
    `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
    'CRON_SECRET=local-dev-cron-secret',
    'NEXT_PUBLIC_SITE_URL=http://localhost:3000',
    '',
  ].join('\n');

  writeFileSync('apps/web/.env.local', env);
  ok('written');

  // --- schema + data ------------------------------------------------------
  step('Applying migrations and seeding');
  run('supabase', ['db', 'reset']);
  ok('schema + market types + rule set v1');

  process.env.NEXT_PUBLIC_SUPABASE_URL = apiUrl;
  process.env.SUPABASE_SERVICE_ROLE_KEY = serviceKey;
  run('pnpm', ['db:seed:dev']);

  console.log(`
Ready.

  pnpm dev            then open http://localhost:3000

Sign up with any email — local auth does not send or verify anything. Then create a
league and predict; the seeded season has 20 teams across 3 matchweeks.

  pnpm drill          predict → lock → settle → leaderboard → correction, end to end
  pnpm ui:smoke       drives a browser through every page (needs the app running)
  supabase studio     browse the database at http://127.0.0.1:54323

To see the settled and live states, run \`pnpm drill\` — it plays a fixture through
to full time, so /live and the leaderboard have something real in them.
`);

  if (!existsSync('node_modules')) {
    console.log('  Note: run `pnpm install` first — node_modules is missing.\n');
  }
}

main();
